spring.application.name=01_microservicio_cursos

#config Server
spring.cloud.config.uri=http://localhost:8888

#puerto del microservicio (8090, 8091 para otras instancias)
#server.port=8080 #para arrancar las 3 instancias le meto el puerto por run configuration y arranco 3 desde eclipse

#eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
