spring.application.name=02_microservicio_formacion
server.port=8081
#config Server
spring.cloud.config.uri=http://localhost:8888

#eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
